### ISSUE TITLE
没成功，nastool 不断重启

### ISSUE THREAD

**Issue by eason666888** [sgpublic/xunlei-nastools#2]
有哪里不对么？

**Comment by eason666888** [comment]
![Uploading 新建位图图像.jpg…]()
![Uploading 新建位图图像2.jpg…]()

**Comment by eason666888** [comment]
![新建位图图像](https://github.com/sgpublic/xunlei-nastools/assets/103944546/d95af7de-2491-40de-be69-d373e4265f32)

![新建位图图像2](https://github.com/sgpublic/xunlei-nastools/assets/103944546/b187df4e-2fdb-42bb-98c7-b62386d2d179)

**Comment by sgpublic** [comment]
对照 readme 中的命令重新 clone

注：此仓库仅在 3.3.x 测试通过

**Comment by sgpublic** [comment]
由于长时间没有收到进一步回复，我将关闭这个 issue，如果需要进一步讨论请 reopen 此 issue。
