### ISSUE TITLE
勾选xunlei，但实际nas-tools触发的还是qbittorrent

### ISSUE THREAD

**Issue by hjdlearn** [sgpublic/xunlei-nastools#4]
界面能显示，也可以选择xunlei，但是实际下载任务还是会到默认的qbit，不知道如何调整才能实现订阅后在迅雷侧触发自动下载。
另外下载器nas-迅雷点击测试时，无论输入啥都能测试成功来着。
![image](https://github.com/user-attachments/assets/a036ed03-fa8b-4823-b0a8-23370321b116)

**Comment by sgpublic** [comment]
此仓库仅在 nas-tools 3.x 测试，请检查 nas-tools 版本。

**Comment by hjdlearn** [comment]
感谢，想起来之前为了屏蔽网站的设置，选了2.9.1的版本
![11CE740C](https://github.com/user-attachments/assets/0f2f482a-a697-4ebe-b2a3-9bc2a43df5b1)
