### ISSUE TITLE
获取状态出错：从 HTML 中获取 uiauth 失败

### ISSUE THREAD

**Issue by fangz1230** [sgpublic/xunlei-nastools#7]
我迅雷使用的是[cnk3x/xunlei](https://github.com/cnk3x/xunlei)
并且按照       [迅雷下载提供器安装和配置](https://github.com/opennaslab/kubespider/tree/f55eab6a931d1851d5cbe2b6467d7dde96bffdef/docs/zh/user_guide/thunder_install_config)       修改了`xunlei_get_token.js`
但提示下载器连接测试失败
![1732693846025](https://github.com/user-attachments/assets/52268bd8-ce52-4c47-a8c9-5024a8de8690)

**Comment by sgpublic** [comment]
请提供一下迅雷版本

**Comment by sgpublic** [comment]
版本问题详见：[cnk3x/xunlei - XL_PREVENT_UPDATE](https://github.com/cnk3x/xunlei#:~:text=%E7%94%A8%E6%88%B7%E7%BB%84ID-,XL_PREVENT_UPDATE,-%23%E6%98%AF%E5%90%A6%E9%98%BB%E6%AD%A2)，这与我的仓库无关，不再讨论。

你题到的问题本质上是我项目的bug，这段时间没时间修，不过更新迅雷到最新版本可以从侧面解决这个问题。

**Comment by sgpublic** [comment]
已修复，拉取最新 commit 即可
